#!/bin/bash
CC16="/usr/bin/watcom/binl64/wcc"		#Compiler
CC16_Flags="-s -wx -ms -zl -zq"
LD16="/usr/bin/watcom/binl64/wlink"	#Linker

nasm -f bin asm/boot.asm -o build/boot.bin
	echo "DONE...files.bin Created"

nasm -f obj -o obj/asm_main.obj asm/main.asm
nasm -f obj -o obj/asm_print.obj asm/print.asm
nasm -f obj -o obj/asm_delay.obj asm/delay.asm
nasm -f obj -o obj/asm_clear.obj asm/clear.asm
	echo "DONE...files.obj Created"

$CC16 $CC16_Flags c/main.c
$CC16 $CC16_Flags c/stdio.c
	mv main.o obj/main.o
	mv stdio.o obj/stdio.o
	echo "DONE...compiling"

$LD16 name kernel.bin file obj/asm_main.obj, obj/asm_print.obj, obj/main.o, obj/stdio.o, obj/asm_delay.obj, obj/asm_clear.obj @linker.lnk
	mv kernel.bin build/kernel.bin
	echo "DONE...linking"
	
dd if=/dev/zero of=build/main.img bs=512 count=2880
	echo "DONE...main.img Created"

mkfs.fat -F 12 -n "GOOS" build/main.img
	echo "DONE...Formated to FAT12"

dd if=build/boot.bin of=build/main.img conv=notrunc
	echo "DONE...Bootloader Copied No Truncate"

mcopy -i build/main.img build/kernel.bin "::KERNEL.BIN"
	echo "DONE...Kernel Copied No Truncate"

qemu-system-i386 -fda build/main.img
	echo "DONE..."